server:
  port: ${port:8080}

spring:
  application:
    name: compolybot
  data:
    mongodb:
      uri: mongodb://localhost:27017/compolyBot
      auto-index-creation: true


bot:
  telegramToken:
  auto-delete-messages:
    fixed-rate: 60_000

cat-api:
  apiKey:


logging:
  file:
    name: ${log.dir:/tmp}/compolybot.main.log
